### ISSUE TITLE
Vulkan-Hpp doesn't build with 1.1.105 spec update due to platform dependency error in full_screen_exclusive extension code

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Hpp#309]
Building with the just released 1.1.105 spec update, the hpptest app gets these clang (and corresponding gcc) errors:

> In file included from hpptest.cpp:1:
> ./vulkan/vulkan.hpp:3875:16: error: use of undeclared identifier 'VK_FULL_SCREEN_EXCLUSIVE_DEFAULT_EXT'; did you mean 'VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT'?
>     eDefault = VK_FULL_SCREEN_EXCLUSIVE_DEFAULT_EXT,
>                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT
> Vulkan-Docs/include/vulkan/vulkan_core.h:148:5: note: 'VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT' declared here
>     VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT = -1000255000,
>     ^
> In file included from hpptest.cpp:1:
> ./vulkan/vulkan.hpp:3876:16: error: use of undeclared identifier 'VK_FULL_SCREEN_EXCLUSIVE_ALLOWED_EXT'
>     eAllowed = VK_FULL_SCREEN_EXCLUSIVE_ALLOWED_EXT,
>                ^
> ./vulkan/vulkan.hpp:3877:19: error: use of undeclared identifier 'VK_FULL_SCREEN_EXCLUSIVE_DISALLOWED_EXT'
>     eDisallowed = VK_FULL_SCREEN_EXCLUSIVE_DISALLOWED_EXT,
>                   ^
> ./vulkan/vulkan.hpp:3878:30: error: use of undeclared identifier 'VK_FULL_SCREEN_EXCLUSIVE_APPLICATION_CONTROLLED_EXT'
>     eApplicationControlled = VK_FULL_SCREEN_EXCLUSIVE_APPLICATION_CONTROLLED_EXT
>                              ^
> 4 errors generated.

Even though the VK_EXT_full_screen_exclusive extension is marked as platform="win32", and as a result the VkFullScreenExclusiveEXT enum is defined only in vulkan_win32.h, the generated vulkan.hpp puts the derived C++ type definition in platform-independent code. Based on comparison with the header for VkSurfaceFullScreenExclusiveWin32InfoEXT, which is in platform-dependent code, I suspect the Hpp generator is not treating the platform= attribute in the same way as the C header generation scripts. The language from the registry document is:

> * attr:platform - optional. Indicates that the extension is specific to the platform identified by the attribute value, and should be emitted conditional on that platform being available, in a platform-specific header, etc. The attribute value must be the same as one of the tag:platform tag:name attribute values.

Tagging in @cubanismo because it's his extension.

**Comment by asuessenbach** [comment]
You're right, the platform protection specified in the extension was not carried over to the corresponding enum classes. This is fixed with PR #310.

Note: While fixing this issue, we had to generate the vulkan headers on our own, and then the class VkPhysicalDeviceSurfaceInfo2KHR was declared in both vulkan_core.h and vulkan_win32.h.
Is there a glitch in the header generation, or did we do something wrong here?

**Comment by oddhack** [comment]
@asuessenbach I'll take a look at that; it sounds like an error in the frontend setup that specifies how functionality is segregated across the different headers. I don't have the ability to build in a win32 environment so that's hard for me to detect - thanks for picking up on it.

**Comment by oddhack** [comment]
@asuessenbach I fixed, AFAICT, the issue in Vulkan-Docs (at least, I can compile all the platform C headers together using dummy external type definitions for win32 and a few other platforms as needed) and tried to rebuild. Made a little progress, but now

> VULKAN_HPP_INLINE std::string to_string( FullScreenExclusiveEXT value )

generates a compilation error because it is defined outside the VK_USE_PLATFORM_WIN32_KHR protection, but uses the FullScreenExclusiveEXT type defined inside the protection.

**Comment by oddhack** [comment]
Problem code fragment:

> #ifdef VK_USE_PLATFORM_WIN32_KHR
>   enum class FullScreenExclusiveEXT
>   {
>     eDefault = VK_FULL_SCREEN_EXCLUSIVE_DEFAULT_EXT,
>     eAllowed = VK_FULL_SCREEN_EXCLUSIVE_ALLOWED_EXT,
>     eDisallowed = VK_FULL_SCREEN_EXCLUSIVE_DISALLOWED_EXT,
>     eApplicationControlled = VK_FULL_SCREEN_EXCLUSIVE_APPLICATION_CONTROLLED_EXT
>   };
> #endif /*VK_USE_PLATFORM_WIN32_KHR*/
>
>   VULKAN_HPP_INLINE std::string to_string( FullScreenExclusiveEXT value )
>   {
>     switch ( value )
>     {
>       case FullScreenExclusiveEXT::eDefault : return "Default";
>       case FullScreenExclusiveEXT::eAllowed : return "Allowed";
>       case FullScreenExclusiveEXT::eDisallowed : return "Disallowed";
>       case FullScreenExclusiveEXT::eApplicationControlled : return "ApplicationControlled";
>       default: return "invalid";
>     }
>   }

And resulting errors:

> In file included from hpptest.cpp:1:0:
> ./vulkan/vulkan.hpp:3883:44: error: ‘vk::to_string’ declared as an ‘inline’ variable
>    VULKAN_HPP_INLINE std::string to_string( FullScreenExclusiveEXT value )
>                                             ^~~~~~~~~~~~~~~~~~~~~~
> ./vulkan/vulkan.hpp:3883:44: error: ‘always_inline’ attribute ignored [-Werror=attributes]
> ./vulkan/vulkan.hpp:3883:44: error: ‘std::__cxx11::string vk::to_string’ redeclared as different kind of symbol
> ./vulkan/vulkan.hpp:3863:33: note: previous declaration ‘std::__cxx11::string vk::to_string(vk::FrontFace)’
>    VULKAN_HPP_INLINE std::string to_string( FrontFace value )
>                                  ^~~~~~~~~
> ./vulkan/vulkan.hpp:3883:44: error: ‘FullScreenExclusiveEXT’ was not declared in this scope
>    VULKAN_HPP_INLINE std::string to_string( FullScreenExclusiveEXT value )
>                                             ^~~~~~~~~~~~~~~~~~~~~~
> hpptest.cpp:7:1: error: expected ‘}’ at end of input
>  }
>  ^
> cc1plus: all warnings being treated as errors

**Comment by asuessenbach** [comment]
Fixed with PR #311.

**Comment by oddhack** [comment]
Thanks! I've successfully built and test-compiled both C and C++ headers now so closing this.
