### ISSUE TITLE
vulkan-hpp build error C2664 on 1.1.126.0

### ISSUE THREAD

**Issue by natovan** [KhronosGroup/Vulkan-Hpp#452]
I tried to build a Vulkan C++ Windowed Program template. At first it returned error "Outdated Platform Toolset. Update your project to newer toolset". After redirecting to v142 (was v140) and building it again:

```
1>------ Build started: Project: VulkTest, Configuration: Debug x64 ------
1>main.cpp
1>C:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73814,1): error C2664: 'HMODULE LoadLibraryW(LPCWSTR)': cannot convert argument 1 from 'const char [13]' to 'LPCWSTR'
1>C:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73814,32): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\libloaderapi.h(665,1): message : see declaration of 'LoadLibraryW'
1>Done building project "VulkTest.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

I think this is a C++ standard problem.

Using Visual Studio 2019 16.4.0

**Comment by asuessenbach** [comment]
This has already been resolved with #422. Unfortunately, that change didn't make it into the latest Vulkan SDK.

**Comment by asuessenbach** [comment]
@natovan Would you mind closing this issue if it's resolved or providing more details if not?

**Comment by MythreyaK** [comment]
I have the same issue, same error as described above. This doesn't seem to happen with CMake projects though as the CMake project links against the library directly, so no dynamic loading required. I'm not sure how to replicate this issue with CMake.

**Comment by mtavenrath** [comment]
@MythreyaK Do you see the issue with Vulkan-Hpp provided in the latest Vulkan-SDK or also with Vulkan-Hpp in this github repository?

**Comment by MythreyaK** [comment]
The latest SDK release version `1.1.126.0`. Haven't built this repo though, didn't see the need to. I noticed that the fix has been merged; hope it's released soon!

**Comment by asuessenbach** [comment]
@MythreyaK The issue described here should definitely not be a static vs. dynamic loading issue.
But you're right, all the samples provided are a bit sloppy with that: they all link against the static lib, and most of them also dynamically load the dll. That will be resolved with PR #462.

**Comment by MythreyaK** [comment]
Oh I see! 

Out of curiosity, where do these load the library dynamically? I don't see any calls to `DynamicLoader` anywhere. in `vulkan.hpp` (assuming of course that `VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=1`). 

On a sidenote, if I may ask, apart from `vulkan-tutorial.com`, which resources do you think are perfect to learn Vulkan with CPP?

**Comment by mtavenrath** [comment]
> The latest SDK release version `1.1.126.0`. Haven't built this repo though, didn't see the need to. I noticed that the fix has been merged; hope it's released soon!
No need to build Vulkan-hpp nor wait for the next SDK. The current header will work with the 1.1.26.0.
https://raw.githubusercontent.com/KhronosGroup/Vulkan-Hpp/master/vulkan/vulkan.hpp

**Comment by asuessenbach** [comment]
> Out of curiosity, where do these load the library dynamically? I don't see any calls to DynamicLoader anywhere. in vulkan.hpp (assuming of course that VULKAN_HPP_DISPATCH_LOADER_DYNAMIC=1).

Please have a look at tests/DispatchLoaderDynamic. And it's also described in the Readme.md (https://github.com/KhronosGroup/Vulkan-Hpp#extensions--per-device-function-pointers)

**Comment by MythreyaK** [comment]
I tried to use the default loader and storage facility, but I keep getting a linker error `unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic"`. 

My header file looks like so 
```
// main.hpp
#ifndef _HEADER_MAIN_
#define _HEADER_MAIN_
... other std:: includes ...
#define VK_USE_PLATFORM_WIN32_KHR
#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
#define VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE
#include <vulkan/vulkan.hpp>

...
class MyClass ...
```
```
// main.cpp
#include "main.hpp"
// by this time, vulkan defines should set up glfw right for vulkan
#include <GLFW/glfw.h>

...
// in the class constructor, 
  vk::DynamicLoader dl;
  PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr = dl.getProcAddress<PFN_vkGetInstanceProcAddr>("vkGetInstanceProcAddr");
  VULKAN_HPP_DEFAULT_DISPATCHER.init(vkGetInstanceProcAddr);
```

Did I miss or misunderstand something?

**Comment by mtavenrath** [comment]
@natovan The issue you're describing should be resolved with the usage of TEXT for the filename in vulkan.hpp. Check if you have this line in your header.

      m_library = LoadLibrary( TEXT( "vulkan-1.dll" ) );

If the issue persists can you give us more details on your build environment and reopen the bug?

>At first it returned error "Outdated Platform Toolset. Update your project to newer toolset"
This issue occurs every time you update your Visual Studio which installs a new toolkit in this process. Either you have to recreate the cmake solution or manually change the platform. It's not an Vulkan-Hpp issue.

**Comment by MythreyaK** [comment]
Can confirm the latest version solves this issue for me. It includes the `TEXT` fix. 

@natovan If installation is not possible, then replacing the header with the one that can be downloaded here also does the trick, as @mtavenrath previously mentioned. 
> https://raw.githubusercontent.com/KhronosGroup/Vulkan-Hpp/master/vulkan/vulkan.hpp
