### ISSUE TITLE
vk::DispatchLoaderDynamic.operator=(vk::Instance &) missing after upgrading from Vulkan SDK 1.1.121.2 to 1.1.126.0

### ISSUE THREAD

**Issue by Icedude907** [KhronosGroup/Vulkan-Hpp#454]
Previously, on Vulkan SDK version 1.1.121.2 the code
```
vk::DispatchLoaderDynamic dld;
dld.operator=(instance.get()); //My instance is a vk::UniqueInstance
```
Worked without any problems.

However, when compiling on mingw64-gcc using Vulkan SDK 1.1.126.0 I get this long winded error message:
```
In file included from xyz.cpp:
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp:73858:5: error: 'HMODULE' does not name a type
     HMODULE m_library;
     ^~~~~~~
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp: In constructor 'vk::DynamicLoader::DynamicLoader()':
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp:73814:7: error: 'm_library' was not declared in this scope
       m_library = LoadLibrary( "vulkan-1.dll" );
       ^~~~~~~~~
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp:73814:19: error: 'LoadLibrary' was not declared in this scope
       m_library = LoadLibrary( "vulkan-1.dll" );
                   ^~~~~~~~~~~
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp: In destructor 'vk::DynamicLoader::~DynamicLoader()':
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp:73831:12: error: 'm_library' was not declared in this scope
       if ( m_library )
            ^~~~~~~~~
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp:73836:9: error: 'FreeLibrary' was not declared in this scope
         FreeLibrary( m_library );
         ^~~~~~~~~~~
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp: In member function 'T vk::DynamicLoader::getProcAddress(const char*) const':
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp:73847:33: error: 'm_library' was not declared in this scope
       return (T)GetProcAddress( m_library, function );
                                 ^~~~~~~~~
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp:73847:17: error: there are no arguments to 'GetProcAddress' that depend on a template parameter, so a declaration of 'GetProcAddress' must be available [-fpermissive]
       return (T)GetProcAddress( m_library, function );
                 ^~~~~~~~~~~~~~
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp:73847:17: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
xyz.cpp: In member function 'void ThisProgram::setupDebugMessenger()':
xyz.cpp:224:31: error: no matching function for call to 'vk::DispatchLoaderDynamic::operator=(vk::Instance&)'
   DLD.operator=(instance.get());
                               ^
In file included from xyz.cpp:11:
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp:73865:9: note: candidate: 'constexpr vk::DispatchLoaderDynamic& vk::DispatchLoaderDynamic::operator=(const vk::DispatchLoaderDynamic&)'
   class DispatchLoaderDynamic
         ^~~~~~~~~~~~~~~~~~~~~
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp:73865:9: note:   no known conversion for argument 1 from 'vk::Instance' to 'const vk::DispatchLoaderDynamic&'
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp:73865:9: note: candidate: 'constexpr vk::DispatchLoaderDynamic& vk::DispatchLoaderDynamic::operator=(vk::DispatchLoaderDynamic&&)'
A:\Coding\Libraries\VulkanSDK\1.1.126.0\Include/vulkan/vulkan.hpp:73865:9: note:   no known conversion for argument 1 from 'vk::Instance' to 'vk::DispatchLoaderDynamic&&'
```

I haven't defined anything that would make vulkan.hpp deviate from its default behaviour, so I am confused as to why this has happened.
A quick search for operator= on Github's commit search hasn't yielded any results either.

Thank you in advance for any assistance.

**Comment by asuessenbach** [comment]
I'm not sure what you'd want to achieve with this code: `dld.operator=(instance.get());` There is nothing like a `DispatchLoaderDynamic::operator=(vk::Instance)`
But the error messages you get on HMODULE and m_library has already been resolved with #431.

**Comment by asuessenbach** [comment]
@Icedude907 Would you mind closing this issue if it's resolved or providing more details if not?
