### ISSUE TITLE
(1.1.108.0): MSVC 32-bit compilation, error C2664

### ISSUE THREAD

**Issue by past-due** [KhronosGroup/Vulkan-Hpp#343]
```
C:\VulkanSDK\1.1.108.0\Include\vulkan/vulkan.hpp(56908): error C2664: 
'void vk::DispatchLoaderDynamic::init(VkInstance,PFN_vkGetInstanceProcAddr,VkDevice,PFN_vkGetDeviceProcAddr)': 
cannot convert argument 1 from 'const vk::Instance' to 'VkInstance
```

This appears to have been introduced by #300?

(This is MSVC 2017.)

**Comment by Doozer** [comment]
I get the exact same error, but only when i compile for 32 bit. When i compile the same code in a 64 bit setup it does work without a problem. I am using MSVC 2019 commuinty edition.

**Comment by asuessenbach** [comment]
Resolved with PR #344.
