### ISSUE TITLE
Cannot compile with `NDEBUG` defined

### ISSUE THREAD

**Issue by rjodinchr** [KhronosGroup/Vulkan-Hpp#1254]
When compiling with `NDEBUG` defined, I get the following error:

```
In file included from usr/include/vulkan/vulkan.hpp:6771:
/usr/include/vulkan/vulkan_funcs.hpp:2157:26: error: no member named 'getVkHeaderVersion' in 'vk::DispatchLoaderDynamic'
    VULKAN_HPP_ASSERT( d.getVkHeaderVersion() == VK_HEADER_VERSION );
```

It feels that the [guard](https://github.com/KhronosGroup/Vulkan-Headers/blob/main/include/vulkan/vulkan.hpp#L1273) around `getVkHeaderVersion` is removing the function while the assertion will stay there anyway.

This change has been introduced by b8c57b0a09f7324fec5a7c363f5e26ff4d5a3222

**Comment by rjodinchr** [comment]
I understand what is happening. The bug is on my side:

I have `-DVULKAN_HPP_ASSERT=""` in my build system which is the source of this issue.
