### ISSUE TITLE
vulkan_structs.hpp fails to compile on FreeBSD with -std=c++2b

### ISSUE THREAD

**Issue by litherum** [KhronosGroup/Vulkan-Hpp#1861]
## Steps to reproduce

Create the following file:

```cpp
#include <vulkan/vulkan.hpp>

int main(int argc, char *argv[]) {
    return 0;
}
```

Compile on FreeBSD 14.0 with:
```zsh
% clang++ -I/usr/local/include -std=c++2b test.cpp
```

Compilation fails with:
```
In file included from test.cpp:1:
In file included from /usr/local/include/vulkan/vulkan.hpp:8691:
/usr/local/include/vulkan/vulkan_structs.hpp:16380:9: error: member initializer '__major' does not name a non-static data member or base class
      : major( major_ )
        ^~~~~~~~~~~~~~~
/usr/include/sys/types.h:329:18: note: expanded from macro 'major'
#define major(d)        __major(d)
                        ^~~~~~~~~~
In file included from test.cpp:1:
In file included from /usr/local/include/vulkan/vulkan.hpp:8691:
/usr/local/include/vulkan/vulkan_structs.hpp:16381:9: error: member initializer '__minor' does not name a non-static data member or base class
      , minor( minor_ )
        ^~~~~~~~~~~~~~~
/usr/include/sys/types.h:335:18: note: expanded from macro 'minor'
#define minor(d)        __minor(d)
                        ^~~~~~~~~~
2 errors generated.
```

## Analysis

This is because `vulkan/vulkan.hpp` transitively includes `sys/types.h`, which `#define`s `major()` to `__major()` and `minor()` to `__minor()`:

```cpp
#define major(d)        __major(d)
static __inline int 
__major(dev_t _d) 
{
        return (((_d >> 32) & 0xffffff00) | ((_d >> 8) & 0xff));
}
#define minor(d)        __minor(d)
static __inline int 
__minor(dev_t _d) 
{
        return (((_d >> 24) & 0xff00) | (_d & 0xffff00ff));
}
#define makedev(M, m)   __makedev((M), (m))
static __inline dev_t
__makedev(int _Major, int _Minor)
{
        return (((dev_t)(_Major & 0xffffff00) << 32) | ((_Major & 0xff) << 8) |
            ((dev_t)(_Minor & 0xff00) << 24) | (_Minor & 0xffff00ff));
}
```

and `vulkan/vulkan_structs.hpp` has:

```cpp
  struct ConformanceVersion
  {
    ...
    VULKAN_HPP_CONSTEXPR ConformanceVersion( uint8_t major_ = {}, uint8_t minor_ = {}, uint8_t subminor_ = {}, uint8_t patch_ = {} ) VULKAN_HPP_NOEXCEPT
      : major( major_ )
      , minor( minor_ )
      , subminor( subminor_ )
      , patch( patch_ )
    {
    }
    ...
  public: 
    uint8_t major    = {};
    uint8_t minor    = {};
    ...
  };
```

## Potential fix

These two constructions can't coexist.

- The best solution is probably to update the vulkan.hpp code generator to use brace initialization, which would change `major( major_ )` to `major { major_ }`, thereby solving the problem.
- Alternatively, the code generator could just use a different constructor parameter name.
- Or the header could stop including `sys/types.h` (though this is probably difficult and brittle).
- Alternatively, perhaps this bug could be kicked over to FreeBSD, which could stop `#define`ing `major()` and `minor()`, or guard the `#define` behind a macro (like how `NOMINMAX` does on Windows).

## Workaround

The most straightforward workaround is to use `-std=c++20` instead of `c++2b` (or `gnu++20` instead of `gnu++2b`). This workaround will become less and less practical as C++2b becomes more common.

**Comment by sharadhr** [comment]
> transitively includes sys/types.h, which #defines major() to __major() and minor() to __minor()

Ugh, yikes. I'm guessing it comes from `#include <cstring>` which eventually gets to `sys/types.h`. 

There's work to move to `import std; which would *properly* resolve this, but I'm waiting for tooling support to improve—CMake 3.30 release is a couple of months out yet (still), as are compilers, especially GCC.

I think moving to brace initialisation throughout is a good idea, however, even if this macro leaks through.

**Comment by asuessenbach** [comment]
Thanks for reporting this somewhat strange thing!

I think, the best solution would be to "kick it over to FreeBSD", as just defining such very basic things should be a NoGo! I can very well imagine, that something like major(x) and minor(x) are used often out in the wild. Yes, pretty close to the min/max issue  from windows.
But in the meantime, I'll change to brace initialization.

**Comment by jbeich** [comment]
As [downstream package](https://www.freshports.org/graphics/vulkan-headers) maintainer I can't reproduce on FreeBSD 13.3 (libc++ 17) and 14.1 (libc++ 18). `git bisect` points to https://github.com/llvm/llvm-project/commit/e7e371188513 but it's not obvious why. `<sys/types.h>` is still implicitly included (confirmed by injecting `#error`) but doesn't trigger the `major` + `minor` macro conflict.

**Comment by jbeich** [comment]
After comparing `-E` (preprocessed) output:
```diff
     constexpr ConformanceVersion( uint8_t major_ = {}, uint8_t minor_ = {}, uint8_t subminor_ = {}, uint8_t patch_ = {} ) noexcept
-      : __major(major_)
-      , __minor(minor_)
+      : major( major_ )
+      , minor( minor_ )
       , subminor( subminor_ )
       , patch( patch_ )
     {
```

**Comment by jbeich** [comment]
Also, downstream had a related workaround in the past:
```bsdmake
post-patch:
# XXX Drop after FreeBSD 12.4 EOL around 2023-12-31
	@if [ -L /usr/include/sched.h ]; then \
		 ${REINPLACE_CMD} $$'/^namespace/i\\\n#undef major\\\n#undef minor\\\n\\\n' \
			  ${WRKSRC}/include/vulkan/vulkan_structs.hpp; \
	fi
```

**Comment by jbeich** [comment]
> This workaround will become less and less practical as C++2b becomes more common.

`-std=c++23` requires Clang/libc++ >= 17 where the error doesn't occur.

**Comment by jbeich** [comment]
Nevermind, even if Clang/libc++ >= 17 is fine GCC/libstdc++ is still affected. Switching to braced initialization does help.
```
$ pkg install gcc13
$ g++13 -I/usr/local/include -std=c++2b test.cpp
In file included from /usr/include/sched.h:33,
                 from /usr/include/pthread.h:46,
                 from /usr/local/lib/gcc13/include/c++/x86_64-portbld-freebsd13.2/bits/gthr-default.h:35,
                 from /usr/local/lib/gcc13/include/c++/x86_64-portbld-freebsd13.2/bits/gthr.h:148,
                 from /usr/local/lib/gcc13/include/c++/ext/atomicity.h:35,
                 from /usr/local/lib/gcc13/include/c++/bits/locale_classes.h:41,
                 from /usr/local/lib/gcc13/include/c++/locale:41,
                 from /usr/local/lib/gcc13/include/c++/format:42,
                 from /usr/local/include/vulkan/vulkan_to_string.hpp:14,
                 from /usr/local/include/vulkan/vulkan.hpp:6155,
                 from test.cpp:1:
/usr/local/include/vulkan/vulkan_structs.hpp: In constructor 'constexpr vk::ConformanceVersion::ConformanceVersion(uint8_t, uint8_t, uint8_t, uint8_t)':
/usr/local/include/vulkan/vulkan_structs.hpp:16380:9: error: class 'vk::ConformanceVersion' does not have any field named '__major'
16380 |       : major( major_ )
      |         ^~~~~
/usr/local/include/vulkan/vulkan_structs.hpp:16381:9: error: class 'vk::ConformanceVersion' does not have any field named '__minor'
16381 |       , minor( minor_ )
      |         ^~~~~

$ sed -i '.bak' -E '/\<m(aj|in)or\(/y/()/{}/' /usr/local/include/vulkan/vulkan_structs.hpp
$ g++13 -I/usr/local/include -std=c++2b test.cpp
$ echo $?
0
```
