### ISSUE TITLE
vulkan_raii.hpp fails to compile in version 1.3.246 due to broken ShaderEXT constructor

### ISSUE THREAD

**Issue by DonutVikingChap** [KhronosGroup/Vulkan-Hpp#1549]
One of the constructors of ShaderEXT in `vulkan_raii.hpp` currently refers to a non-existent member "`m_constructorSuccessCode`", causing a compilation error. I noticed this when compiling my project after installing the latest version of the Vulkan headers (1.3.246) on EndeavourOS, but the problem should apply to all platforms and compilers. I checked the Vulkan-Headers repository and the issue appears to still be present in the latest commit: https://github.com/KhronosGroup/Vulkan-Headers/blob/63af1cf1ee906ba4dcd5a324bdd0201d4f4bfd12/include/vulkan/vulkan_raii.hpp#L10192

Picture of the error:
![image](https://user-images.githubusercontent.com/5530607/229286708-44dba127-4bb4-4f1c-a62d-5f8093e2fd78.png)

How to reproduce:
1. Install vulkan-headers 1.3.246
2. Include `<vulkan/vulkan_raii.hpp>` in any .cpp file and try to compile
