### ISSUE TITLE
How to use VK_NO_PROTOTYPES and dynamic dispatching?

### ISSUE THREAD

**Issue by lordalcol** [KhronosGroup/Vulkan-Hpp#377]
I am trying to use `vulkan.hpp` on Android. I used to use an old version of it (based on Vulkan 1.0) and the vulkan_wrapper provided by the Android NDK without issues.

With the current version, `VK_NO_PROTOTYPES` is defined, and `vulkan.hpp` is complaining that   `typedef NeedExplicitDispatchLoader DispatchLoaderDefault;` is not defined.

Is there an example that shows how to use the dynamic dispatch?
Or is there a different way to use vulkan.hpp on Android?

Thanks,
Lorenzo

**Comment by res2k** [comment]
1. Create & set up an instance of `vk::DispatchLoaderDynamic`
2. Pass that instance as the last parameter when calling any of the C++ wrapper methods

**Comment by res2k** [comment]
Alternatively (and probably simpler: vulkan_wrapper defines the Vulkan "functions" as a bunch of function pointers, if you can `#undef`ine `VK_NO_PROTOTYPES` before including `vulkan.hpp` those pointers will be used.

**Comment by asuessenbach** [comment]
@lordalcol Does the comment from @res2k resolve your issue?

**Comment by mtavenrath** [comment]
Take a look at the https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/tests/DispatchLoaderDynamic/DispatchLoaderDynamic.cpp
on how to use the dynamic dispatcher in a nearly fully transparent manner.

The short summary is either ```#define VK_NO_PROTOTYPES``` or ```#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1``` and add ```VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE;``` to any compilation unit. This will replace the use of the static dispatcher by the dynamic dispatcher and provides storage for the function pointers. Afterwards follow the test instruction on how to initialize the function pointers. calling init(device) is optional since init(instance) will initialize all function pointers.

**Comment by lordalcol** [comment]
@asuessenbach  and @mtavenrath  I am working on this right now, I wil let you know which one works!

**Comment by asuessenbach** [comment]
Heard nothing back, assuming the issue is resolved.

**Comment by InigoLiceranzu** [comment]
I wonder if @lordalcol found a solution as I felt in the same issue.

**Comment by Ignitron** [comment]
I have incurred in the same issue as @lordalcol. I am trying to build on android with ndk 22.1.7171670

This is how I actually wrote my "ApplicationWrapper.h" file header for target android:

----------------------------------------------
#pragma once

#define VK_USE_PLATFORM_ANDROID_KHR
#include <vulkan_wrapper.h>
#include <vulkan/vulkan.hpp>

----------------------------------------------

This file is included in several files over the project.

This is the exact error that I get:

![image](https://user-images.githubusercontent.com/13272741/145653685-b1ef9f30-b365-4005-82b3-2972f2e82fe8.png)

I have tried with #undef VK_NO_PROTOTYPES and every other tip mentioned above without success.

Please, any clue about it will be greatly welcomed.

**Comment by res2k** [comment]
> Please, any clue about it will be greatly welcomed.

`vulkan_wrapper.h` #defines `VK_NO_PROTOTYPES`. So you need to `#undef` that _right after_ that header and _before_ `vulkan.hpp`.

**Comment by Ignitron** [comment]
Yup, tried that too. In that case I get this subsequent error:
In file included from ../../../../src/main/cpp/engine/core/ApplicationWrapper.h:39:
.../Android/sdk/ndk/22.1.7171670/sources/third_party/vulkan/src/include/vulkan/vulkan.hpp:650:14: error: no member named 'vkCmdBeginConditionalRenderingEXT' in the global namespace; did you mean simply 'vkCmdBeginConditionalRenderingEXT'?

**Comment by res2k** [comment]
Looking at `vulkan_wrapper.h` I see only a subset of Vulkan extension functions being defined. The mentioned `vkCmdBeginConditionalRenderingEXT` is not one of them.
However, `vulkan.hpp` expects a definition of all the supported functions, used or not.

The solution, if you want to continue using the default "static" dispatcher, would be to provide a definition of `vkCmdBeginConditionalRenderingEXT` (and any another missing function), similar to what `vulkan_wrapper.h` does:
`extern PFN_vkCmdBeginConditionalRenderingEXT vkCmdBeginConditionalRenderingEXT;`

**Comment by Ignitron** [comment]
Oh, that absolutely makes sense to me!. Regarding the use of an "static" dispatcher, that implicitly says there is a different way to do it. Which one would be the way to use a dynamic dispatcher, is that much more  complex? Do we have an example? what are the benefits? Sorry for the bunch of questions and so much thanks for helping out!.

**Comment by res2k** [comment]
Right, there's a different way. Let's call it an "alternative" or "custom" dispatcher (since it could be "dynamic", but does not necessarily have to be so).
Basically, what this would be is a class, with it's members providing access the different `vkXXX` APIs.
As far as as examples go... actually, `DispatchLoaderStatic` from `vulkan.hpp` would be an example.
Or in newer Vulkan-Hpp versions you can find a `DispatchLoaderDynamic` as well.
Once you have an alternative dispatcher, you'll have to pass it's instance to each Vulkan-Hpp method call - at least in the Vulkan-Hpp version contained in the NDP.

Speaking of newer Vulkan-Hpp: I recommend you take a look at such a newer version. For one, because of said `DispatchLoaderDynamic`. However, newer versions allow the specify a "default dispatcher" via preprocessor macros, which can be more convenient than explicitly passing your dispatcher into any call.

**Comment by InigoLiceranzu** [comment]
After mapping all the methods there is still something else missing regarding the dispatcher which feels somehow being wrong. I went for the static approach.
![Screenshot 2021-12-12 at 17 56 15](https://user-images.githubusercontent.com/84381069/145721675-212db174-1aef-4ac1-af22-4f84b6a59caf.png)
