### ISSUE TITLE
Compilation error in vulkan.hpp generated for 1.0.25 spec

### ISSUE THREAD

**Issue by peterazmanov** [KhronosGroup/Vulkan-Hpp#36]
After generation of `vulkan.hpp` and manually fixing issue #27, I get following error:
```
/home/pa/.../vulkan/vulkan.hpp: In constructor ‘vk::DebugReportLayerFlagsEXT::DebugReportLayerFlagsEXT(uint64_t)’:
/home/pa/.../vulkan/vulkan.hpp:8533:16: error: ‘eDebugReportLayerFlagsEXT’ is not a member of ‘vk::StructureType’
       : sType( StructureType::eDebugReportLayerFlagsEXT )
                ^~~~~~~~~~~~~
```

This happens due to `writeStructConstructor` in `VulkanHppGenerator.cpp`. It initializes `sType` member of 'structure types' to `StructureType::e<name>`. For `VkDebugReportLayerFlagsEXT` specification states:
```
Must be VK_STRUCTURE_TYPE_DEBUG_REPORT_VALIDATION_FLAGS_EXT
```
which corresponds to `StructureType::eDebugReportValidationFlagsEXT`.

With newer version of specification it is no longer the case: structures' names are changed and the `writeStructConstructor` logics doesn't fail (checked for 1.0.28).

**Comment by mtavenrath** [comment]
Vulkan-Hpp now works with spec 1.0.29. Closing.
