### ISSUE TITLE
"'FreeLibrary': identifier not found" error message in 1.1.126.0

### ISSUE THREAD

**Issue by deadshot465** [KhronosGroup/Vulkan-Hpp#434]
So I decided to rewrite a small project using 1.1.126.0 instead of a previous version (1.1.108.0). However, when I tried to compile my program, a bunch of error messages appeared and the program failed to compile:
```
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73858,22): error C3646: 'm_library': unknown override specifier
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73858,22): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73847,33): error C3861: 'm_library': identifier not found
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73847,33): message : This diagnostic occurred in the compiler generated function 'T vk::DynamicLoader::getProcAddress(const char *) noexcept const'
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73814,7): error C2065: 'm_library': undeclared identifier
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73814,19): error C3861: 'LoadLibrary': identifier not found
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73819,19): error C2065: 'm_library': undeclared identifier
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73831,12): error C2065: 'm_library': undeclared identifier
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73836,22): error C2065: 'm_library': undeclared identifier
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73836,9): error C3861: 'FreeLibrary': identifier not found
1>Window.cpp
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73858,22): error C3646: 'm_library': unknown override specifier
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73858,22): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73847,33): error C3861: 'm_library': identifier not found
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73847,33): message : This diagnostic occurred in the compiler generated function 'T vk::DynamicLoader::getProcAddress(const char *) noexcept const'
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73814,7): error C2065: 'm_library': undeclared identifier
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73814,19): error C3861: 'LoadLibrary': identifier not found
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73819,19): error C2065: 'm_library': undeclared identifier
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73831,12): error C2065: 'm_library': undeclared identifier
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73836,22): error C2065: 'm_library': undeclared identifier
1>D:\VulkanSDK\1.1.126.0\Include\vulkan\vulkan.hpp(73836,9): error C3861: 'FreeLibrary': identifier not found
```

The weird thing is that if I change include directories and library directories to point to 1.1.108.0 instead of 1.1.126.0, it will compile without any problem. It also works in 1.1.121.2. If I change the included header file from <vulkan/vulkan.hpp> to <vulkan/vulkan.h>, and directly use C version functions (vkEnumerateInstanceExtensionProperties) instead of Cpp version functions (vk::enumerateInstanceExtensionProperties), it will also compile and execute successfully.

Are there some changes in the hpp file that lead to this problem? Or are there any additional configurations that have to be done in order to use 1.1.126.0 version?

**Comment by asuessenbach** [comment]
That issues has already been resolved with #431.
